In [1]:
import pandas as pd

In [2]:
df_full = pd.read_csv('data/full/hotels_with_clusters.csv', encoding="utf-8")
df_full.head(1)

,location_id,address_obj.state,name_details,latitude,longitude,rating,num_reviews,photo_count,price_level,amenities,...,ranking_ratio,price_level_num,bad_review_share,excellent_review_share,location_rating,rooms_rating,service_rating,value_rating,cleanliness_rating,subratings_confidence
0,278399,Podlaskie Province,Hotel Cristal Bialystok,53.132675,23.15599,4.5,390,221,$,"['Internet', 'Suites', 'Room service', 'Free I...",...,0.0625,1.0,0.015385,0.587179,4.8,4.3,4.7,4.3,4.6,0.5

In [3]:
df = df_full[
    [
        "location_id",
        "name_details",
        "address_obj.city_details",
        "rating",
        "price_level",
        "amenities",
        "styles",
        "description",
    ]
].copy()

df["amenities"] = df["amenities"].fillna("")
df["styles"] = df["styles"].fillna("")
df["description"] = df["description"].fillna("")

df["text"] = (
    df["name_details"].fillna("").astype(str) + " " +
    df["address_obj.city_details"].fillna("").astype(str) + " " +
    df["description"].fillna("").astype(str) + " " +
    df["amenities"].fillna("").astype(str) + " " +
    df["styles"].fillna("").astype(str)
)

df.head(2)

,location_id,name_details,address_obj.city_details,rating,price_level,amenities,styles,description,text
0,278399,Hotel Cristal Bialystok,Bialystok,4.5,$,"['Internet', 'Suites', 'Room service', 'Free I...","['Modern', 'Classic']",,Hotel Cristal Bialystok Bialystok ['Internet'...
1,10050636,Ibis Styles Bialystok,Bialystok,4.5,$,"['Internet', 'Kids Activities', 'Suites', 'Roo...","['Modern', 'Mid-range']",,"Ibis Styles Bialystok Bialystok ['Internet', ..."

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer

texts = df['text'].tolist()

vectorizer = TfidfVectorizer(
    lowercase=True,
    ngram_range=(1, 2),
    max_features=30000,
    min_df=1,
    sublinear_tf=True,
    stop_words='english'
)

X = vectorizer.fit_transform(texts)

print(X.shape)

(135, 9234)

In [5]:
from sklearn.metrics.pairwise import cosine_similarity

def hotel_recomendation(location_id, k = 5):
    idx_list = df.index[df['location_id'] == location_id].tolist()

    idx = idx_list[0]
    scores = cosine_similarity(X[idx], X).flatten()
    best = scores.argsort()[::-1]

    recommendations = []

    for i in best:
        if i == idx:
            continue
        recommendations.append({
            "location_id": int(df.iloc[i]["location_id"]),
            "name": df.iloc[i]["name_details"],
            "score": float(scores[i]),
            "description": df.iloc[i]["description"][:300],
            "amenities": df.iloc[i]["amenities"],
            "styles": df.iloc[i]["styles"],
        })

        if len(recommendations) == k:
            break

    return recommendations

In [6]:
def search_hotels(query, k = 5):
    q = vectorizer.transform([query])
    scores = cosine_similarity(q, X).flatten()

    best = scores.argsort()[::-1][:k]
    
    results = []

    for i in best:
        results.append({
            "location_id": int(df.iloc[i]["location_id"]),
            "name": df.iloc[i]["name_details"],
            "score": float(scores[i]),
            "description": df.iloc[i]["description"][:300],
            "amenities": df.iloc[i]["amenities"],
            "styles": df.iloc[i]["styles"],
        })
    return results

In [7]:
import numpy as np

df = df.replace({np.nan: None})

hotels_metadata = df[
    [
        "location_id",
        "name_details",
        "address_obj.city_details",
        "rating",
        "price_level",
        "description",
        "amenities",
        "styles",
    ]
].to_dict(orient="records")

import joblib
from pathlib import Path

MODEL_DIR = Path("models/tf_idf")
MODEL_DIR.mkdir(parents=True, exist_ok=True)

index_data = {
    "vectorizer": vectorizer,
    "matrix": X,
    "hotels": hotels_metadata,
}

joblib.dump(index_data, MODEL_DIR / "tfidf_index.joblib")
print(f"Zapisano indeks TF-IDF: {MODEL_DIR}/tfidf_index.joblib")

Zapisano indeks TF-IDF: models\tf_idf/tfidf_index.joblib

In [8]:
hotel_id = df.iloc[0]["location_id"]
print(hotel_id)
hotel_recomendation(hotel_id, k=3)

278399

[{'location_id': 21356073,
  'name': 'Mercure Bialystok',
  'score': 0.38820538243524,
  'description': '',
  'amenities': '[\'Shuttle Bus Service\', \'Suites\', \'Room service\', \'Free Internet\', \'Wheelchair access\', \'Restaurant\', \'Bar/Lounge\', \'Pets Allowed\', \'Spa\', \'Public Wifi\', \'Free Wifi\', \'Meeting rooms\', \'Non-smoking rooms\', \'Business center\', \'Fitness center\', \'Laundry Service\', \'Concierge\', \'Banquet Room\', \'Air conditioning\', \'Accessible rooms\', \'Minibar\', \'Conference Facilities\', \'Non-smoking hotel\', \'Safe\', \'Flatscreen TV\', \'Breakfast Buffet\', \'Breakfast Available\', \'Housekeeping\', \'Baggage Storage\', \'Bathrobes\', \'Blackout Curtains\', \'Bottled Water\', \'Breakfast in the Room\', \'Cable / Satellite TV\', \'24-Hour Check-in\', \'Express Check-in / Check-out\', "Children\'s Television Networks", \'Clothes Rack\', \'Desk\', \'Electric Kettle\', \'English\', \'First Aid Kit\', \'Complimentary Toiletries\', \'24-Hour Front Desk\', \'Hair Dryer\', \'Highchairs Available\', \'Interconnected room(s) available\', \'Iron\', \'Ironing Service\', \'Laptop Safe\', \'Outdoor Dining Area\', \'Polish\', \'Private Bathrooms\', \'Paid Private Parking On-site\', \'Radio\', \'Russian\', \'Seating Area\', \'Shoeshine\', \'Sofa\', \'Sofa Bed\', \'Street Parking\', \'Taxi Service\', \'Telephone\', \'Umbrella\', \'Wake Up Service / Alarm Clock\', \'Walk-in Shower\', \'Wardrobe / Closet\']',
  'styles': "['Quaint', 'City View']"},
 {'location_id': 14055281,
  'name': 'B&B HOTEL Gdansk Old Town',
  'score': 0.33632187576956085,
  'description': '',
  'amenities': "['Internet', 'Suites', 'Room service', 'Free Internet', 'Wheelchair access', 'Restaurant', 'Bar/Lounge', 'Pets Allowed', 'Spa', 'Airport transportation', 'Wifi', 'Free Wifi', 'Breakfast included', 'Dry Cleaning', 'Meeting rooms', 'Non-smoking rooms', 'Laundry Service', 'Banquet Room', 'Air conditioning', 'Family Rooms', 'Multilingual Staff', 'Accessible rooms', 'Minibar', 'Conference Facilities', 'Non-smoking hotel', 'Flatscreen TV', 'Breakfast Buffet', 'Breakfast Available', 'Facilities for Disabled Guests', 'Housekeeping', 'ATM On Site', 'Baggage Storage', 'Bath / Shower', 'Bicycle Tours', 'Blackout Curtains', 'Bottled Water', 'Breakfast in the Room', 'Cable / Satellite TV', 'Car Hire', '24-Hour Check-in', 'Coffee Shop', 'Coffee / Tea Maker', 'Complimentary Tea', 'Couples Massage', 'Desk', 'Electric Kettle', 'English', 'Executive Lounge Access', 'Foot Massage', 'Complimentary Instant Coffee', 'Complimentary Toiletries', 'French', '24-Hour Front Desk', 'Full Body Massage', 'Hair Dryer', 'Hand Massage', 'Head Massage', 'Interconnected room(s) available', 'Iron', 'Ironing Service', 'Massage', 'Neck Massage', 'Polish', 'Private Bathrooms', 'Paid Private Parking On-site', 'Paid Public Parking Nearby', 'Russian', 'Seating Area', '24-Hour Security', 'Soundproof Rooms', 'Taxi Service', 'Telephone', 'Ukrainian', 'Wake Up Service / Alarm Clock', 'Walk-in Shower', 'Wardrobe / Closet', 'Wine / Champagne']",
  'styles': "['City View', 'Charming']"},
 {'location_id': 277358,
  'name': 'Novotel Krakow Centrum',
  'score': 0.3349358413542462,
  'description': '',
  'amenities': "['Pool', 'Internet', 'Kids Activities', 'Shuttle Bus Service', 'Suites', 'Room service', 'Free Internet', 'Wheelchair access', 'Restaurant', 'Bar/Lounge', 'Pets Allowed', 'Spa', 'Airport transportation', 'Wifi', 'Public Wifi', 'Free Wifi', 'Dry Cleaning', 'Meeting rooms', 'Hot Tub', 'Non-smoking rooms', 'Tennis Court', 'Business center', 'Fitness center', 'Laundry Service', 'Concierge', 'Banquet Room', 'Air conditioning', 'Family Rooms', 'Multilingual Staff', 'Accessible rooms', 'Refrigerator in room', 'Minibar', 'Conference Facilities', 'Non-smoking hotel', 'Safe', 'Heated pool', 'Flatscreen TV', 'Breakfast Buffet', 'Indoor pool', 'Breakfast Available', 'Parking', 'Facilities for Disabled Guests', 'Housekeeping', 'Sauna', 'ATM On Site', 'Baggage Storage', 'Bath / Shower', 'Bicycle Rental', 'Breakfast in the Room', 'Car Hire', 'Express Check-in / Check-out', 'English', 'Fitness / Spa Locker Rooms', 'Complimentary Instant Coffee', '24-Hour Front Desk', 'Game Room', 'Hair Dryer', 'Hiking', 'Ironing Service', 'Kid-Friendly Buffet', 'Laptop Safe', 'Massage', 'Parking Garage', 'Polish', 'Paid Private Parking On-site', 'Seating Area', '24-Hour Security', 'Steam Room', 'Taxi Service', 'Wake Up Service / Alarm Clock']",
  'styles': "['Business', 'Centrally Located']"}]

In [9]:
hotel_id = df.iloc[1]["location_id"]
hotel_recomendation(hotel_id, k=3)

[{'location_id': 14958792,
  'name': 'Ibis Poznan Centrum',
  'score': 0.44544472888270914,
  'description': '',
  'amenities': "['Internet', 'Kids Activities', 'Suites', 'Room service', 'Free Internet', 'Wheelchair access', 'Restaurant', 'Bar/Lounge', 'Pets Allowed', 'Casino', 'Wifi', 'Public Wifi', 'Free Wifi', 'Breakfast included', 'Meeting rooms', 'Non-smoking rooms', 'Business center', 'Fitness center', 'Laundry Service', 'Banquet Room', 'Air conditioning', 'Family Rooms', 'Multilingual Staff', 'Accessible rooms', 'Conference Facilities', 'Non-smoking hotel', 'Breakfast Buffet', 'Breakfast Available', 'Baggage Storage', '24-Hour Front Desk', 'Polish', 'Paid Private Parking On-site']",
  'styles': "['Family', 'Mid-range']"},
 {'location_id': 1885452,
  'name': 'B&B Hotel Torun',
  'score': 0.3572330839268294,
  'description': '',
  'amenities': "['Internet', 'Free Internet', 'Wheelchair access', 'Pets Allowed', 'Wifi', 'Public Wifi', 'Free Wifi', 'Non-smoking rooms', 'Air conditioning', 'Multilingual Staff', 'Smoking rooms available', 'Accessible rooms', 'Non-smoking hotel', 'Flatscreen TV', 'Breakfast Buffet', 'Breakfast Available', 'Parking', 'Baggage Storage', 'Bath / Shower', 'Clothes Rack', 'Desk', 'English', '24-Hour Front Desk', 'Hair Dryer', 'Polish', 'Paid Private Parking On-site', 'Soundproof Rooms', 'Telephone', 'Wake Up Service / Alarm Clock']",
  'styles': "['Modern', 'Business']"},
 {'location_id': 9884047,
  'name': 'Hotel Mercure Krakow Stare Miasto',
  'score': 0.33933466569371584,
  'description': '',
  'amenities': '[\'Internet\', \'Kids Activities\', \'Suites\', \'Room service\', \'Free Internet\', \'Wheelchair access\', \'Restaurant\', \'Bar/Lounge\', \'Pets Allowed\', \'Airport transportation\', \'Wifi\', \'Public Wifi\', \'Free Wifi\', \'Dry Cleaning\', \'Meeting rooms\', \'Non-smoking rooms\', \'Business center\', \'Fitness center\', \'Laundry Service\', \'Concierge\', \'Banquet Room\', \'Air conditioning\', \'Family Rooms\', \'Multilingual Staff\', \'Accessible rooms\', \'Refrigerator in room\', \'Minibar\', \'Conference Facilities\', \'Non-smoking hotel\', \'Safe\', \'Flatscreen TV\', \'Breakfast Buffet\', \'Breakfast Available\', \'Parking\', \'Facilities for Disabled Guests\', \'Housekeeping\', \'Allergy-free Room\', \'Baggage Storage\', \'Bicycle Rental\', \'Blackout Curtains\', \'Breakfast in the Room\', \'24-Hour Check-in\', \'Express Check-in / Check-out\', "Children\'s Television Networks", \'Complimentary Tea\', \'English\', \'Complimentary Instant Coffee\', \'French\', \'24-Hour Front Desk\', \'German\', \'Hair Dryer\', \'Ironing Service\', \'Kid-Friendly Buffet\', \'Newspaper\', \'Parking Garage\', \'Polish\', \'Private Check-in / Check-out\', \'Paid Private Parking On-site\', \'Paid Private Parking Nearby\', \'Paid Public Parking Nearby\', \'Paid Public Parking On-site\', \'Russian\', \'24-Hour Security\', \'Shoeshine\', \'Soundproof Rooms\', \'Special Diet Menus\', \'Taxi Service\', \'Walk-in Shower\']',
  'styles': "['Business', 'Centrally Located']"}]

In [10]:
hotel_id = df.iloc[2]["location_id"]
hotel_recomendation(hotel_id, k=3)

[{'location_id': 15243198,
  'name': 'Hampton By Hilton Poznan Old Town',
  'score': 0.3383477661100848,
  'description': "Hampton by Hilton Poznan Old Town offers a modern and comfortable stay in the heart of one of Poland’s most historic cities. Located just steps from the Old Market Square, the National Museum, and the city's Royal Castle. Located 10 minutes from the Old Zoo and performances at the Poznan Grand Theat",
  'amenities': "['Internet', 'Free Internet', 'Wheelchair access', 'Bar/Lounge', 'Free Wifi', 'Breakfast included', 'Dry Cleaning', 'Non-smoking rooms', 'Fitness center', 'Laundry Service', 'Air conditioning', 'Non-smoking hotel', 'Safe', 'Breakfast Buffet', 'Baggage Storage', 'Blackout Curtains', 'English', '24-Hour Front Desk', 'Polish', 'Soundproof Rooms', 'Meeting rooms', 'Business center', 'Parking', 'Walk-in Shower']",
  'styles': "['Family', 'Mid-range']"},
 {'location_id': 17678224,
  'name': 'Wynajem Pokoi Bialystok',
  'score': 0.10492064320345462,
  'description': '',
  'amenities': '[]',
  'styles': '[]'},
 {'location_id': 14167696,
  'name': 'Hampton by Hilton Gdansk Old Town',
  'score': 0.09946319256087799,
  'description': 'Hampton by Hilton Gdansk Old Town is located in the heart of the historic Old Town Square. The hotel bears the facade that reflects period architecture, with an interior that offers a contemporary style with modern amenities. Situated right in the middle of the cultural attractions, numerous activit',
  'amenities': '[\'Internet\', \'Free Internet\', \'Wheelchair access\', \'Restaurant\', \'Bar/Lounge\', \'Pets Allowed\', \'Wifi\', \'Public Wifi\', \'Free Wifi\', \'Breakfast included\', \'Dry Cleaning\', \'Meeting rooms\', \'Non-smoking rooms\', \'Business center\', \'Fitness center\', \'Laundry Service\', \'Air conditioning\', \'Multilingual Staff\', \'Accessible rooms\', \'Conference Facilities\', \'Non-smoking hotel\', \'Flatscreen TV\', \'Breakfast Buffet\', \'Breakfast Available\', \'Parking\', \'Baggage Storage\', \'Blackout Curtains\', \'Bottled Water\', \'Express Check-in / Check-out\', \'Desk\', \'English\', \'24-Hour Front Desk\', \'Interconnected room(s) available\', \'Iron\', "Kids\' Meals", \'Parking Garage\', \'Polish\', \'Paid Private Parking On-site\', \'Seating Area\', \'Snack Bar\', \'Taxi Service\', \'Telephone\', \'Family Rooms\', \'Clothes Rack\', \'Electric Kettle\', \'Free Wifi in the Business Center\', \'Happy Hour\', \'Highchairs Available\', \'Laptop Safe\', \'Private Bathrooms\', \'Walk-in Shower\', \'Wardrobe / Closet\', \'Photo Copier / Fax In Business Center\']',
  'styles': "['Charming', 'Business']"}]

In [11]:
search_hotels("activity for children", k=3
              )

[{'location_id': 277647,
  'name': 'Novotel Gdansk Centrum',
  'score': 0.06234651784003262,
  'description': "Novotel Gdansk Centrum is an ideal base for exploring Gdańsk's Old Town. Literally 5 minutes’ walk from Long Market with beautiful sights - The Neptune fountain, the Town Hall, the nearby Crane, the St. Mary's Church and all the unique atmosphere of Gdansk in its most sought after editions, all with",
  'amenities': '[\'Restaurant\', \'Internet\', \'Room service\', \'Free Internet\', \'Wheelchair access\', \'Bar/Lounge\', \'Wifi\', \'Free Wifi\', \'Kids Activities\', \'Fitness center\', \'Dry Cleaning\', \'Meeting rooms\', \'Non-smoking rooms\', \'Business center\', \'Laundry Service\', \'Air conditioning\', \'Family Rooms\', \'Multilingual Staff\', \'Accessible rooms\', \'Conference Facilities\', \'Non-smoking hotel\', \'Safe\', \'Flatscreen TV\', \'Breakfast Buffet\', \'Parking\', \'Facilities for Disabled Guests\', \'Housekeeping\', \'Bath / Shower\', \'Bottled Water\', \'24-Hour Check-in\', \'Express Check-in / Check-out\', \'English\', \'24-Hour Front Desk\', \'Hair Dryer\', "Kids\' Meals", \'Kid-Friendly Buffet\', \'Polish\', \'Paid Public Parking On-site\', \'Shoeshine\', \'Street Parking\', \'Taxi Service\', \'Pets Allowed\', \'Public Wifi\', \'Baggage Storage\', \'Breakfast in the Room\', \'Ironing Service\', \'Newspaper\', \'Paid Private Parking On-site\', \'Special Diet Menus\']',
  'styles': "['Business', 'Green']"},
 {'location_id': 8342267,
  'name': 'Azuria Agroturystyka',
  'score': 0.04431609935792944,
  'description': '',
  'amenities': '[\'Kids Activities\', \'Room service\', \'Free parking\', \'Pets Allowed\', \'Kitchenette\', \'Free Wifi\', \'Tennis Court\', \'Family Rooms\', \'Refrigerator in room\', \'Non-smoking hotel\', \'Bath / Shower\', \'BBQ Facilities\', \'Bicycles Available\', \'Billiards\', \'Board Games / Puzzles\', \'Books, DVDs, Music for Children\', \'Canoeing\', "Children\'s Television Networks", \'Coffee / Tea Maker\', \'Darts\', \'Executive Lounge Access\', \'Fishing\', \'Game Room\', \'Hiking\', \'Indoor Play Area for Children\', "Kids\' Outdoor Play Equipment", \'Kitchenware\', \'Mosquito Net\', \'Outdoor Fireplace\', \'Outdoor Furniture\', \'Picnic Area\', \'Private Check-in / Check-out\', \'Seating Area\', \'Shared Lounge / TV Area\', \'Sofa\', \'Sun Terrace\', \'Wake Up Service / Alarm Clock\']',
  'styles': "['Family', 'Luxury']"},
 {'location_id': 9763242,
  'name': 'ibis Wroclaw Centrum',
  'score': 0.03895047176343764,
  'description': '',
  'amenities': '[\'Internet\', \'Kids Activities\', \'Shuttle Bus Service\', \'Room service\', \'Free Internet\', \'Wheelchair access\', \'Restaurant\', \'Bar/Lounge\', \'Pets Allowed\', \'Airport transportation\', \'Wifi\', \'Public Wifi\', \'Free Wifi\', \'Dry Cleaning\', \'Meeting rooms\', \'Non-smoking rooms\', \'Business center\', \'Fitness center\', \'Laundry Service\', \'Air conditioning\', \'Multilingual Staff\', \'Non-smoking hotel\', \'Safe\', \'Flatscreen TV\', \'Breakfast Buffet\', \'Breakfast Available\', \'Parking\', \'Facilities for Disabled Guests\', \'Housekeeping\', \'Kids Stay Free\', \'Sauna\', \'Baggage Storage\', \'Bicycle Rental\', \'Board Games / Puzzles\', \'Bottled Water\', \'Express Check-in / Check-out\', "Children\'s Television Networks", \'Coffee Shop\', \'Desk\', \'English\', \'24-Hour Front Desk\', \'Game Room\', \'German\', \'Hair Dryer\', \'Highchairs Available\', \'Indoor Play Area for Children\', \'Ironing Service\', \'Patio\', \'Polish\', \'Paid Private Parking On-site\', \'Paid Public Parking Nearby\', \'Secured Parking\', \'Shared Lounge / TV Area\', \'Snack Bar\', \'Taxi Service\', \'Telephone\', \'Video Game Console\', \'Wake Up Service / Alarm Clock\']',
  'styles': "['Mid-range', 'Trendy']"}]

In [12]:
search_hotels("free internet", k=3)

[{'location_id': 5323609,
  'name': 'Noclegi Bydgoszcz - Centrum Onkologii',
  'score': 0.1812754210392287,
  'description': '',
  'amenities': "['Internet', 'Free Internet', 'Wifi', 'Free Wifi']",
  'styles': '[]'},
 {'location_id': 1885452,
  'name': 'B&B Hotel Torun',
  'score': 0.10938220433420558,
  'description': '',
  'amenities': "['Internet', 'Free Internet', 'Wheelchair access', 'Pets Allowed', 'Wifi', 'Public Wifi', 'Free Wifi', 'Non-smoking rooms', 'Air conditioning', 'Multilingual Staff', 'Smoking rooms available', 'Accessible rooms', 'Non-smoking hotel', 'Flatscreen TV', 'Breakfast Buffet', 'Breakfast Available', 'Parking', 'Baggage Storage', 'Bath / Shower', 'Clothes Rack', 'Desk', 'English', '24-Hour Front Desk', 'Hair Dryer', 'Polish', 'Paid Private Parking On-site', 'Soundproof Rooms', 'Telephone', 'Wake Up Service / Alarm Clock']",
  'styles': "['Modern', 'Business']"},
 {'location_id': 14958792,
  'name': 'Ibis Poznan Centrum',
  'score': 0.10931794978598883,
  'description': '',
  'amenities': "['Internet', 'Kids Activities', 'Suites', 'Room service', 'Free Internet', 'Wheelchair access', 'Restaurant', 'Bar/Lounge', 'Pets Allowed', 'Casino', 'Wifi', 'Public Wifi', 'Free Wifi', 'Breakfast included', 'Meeting rooms', 'Non-smoking rooms', 'Business center', 'Fitness center', 'Laundry Service', 'Banquet Room', 'Air conditioning', 'Family Rooms', 'Multilingual Staff', 'Accessible rooms', 'Conference Facilities', 'Non-smoking hotel', 'Breakfast Buffet', 'Breakfast Available', 'Baggage Storage', '24-Hour Front Desk', 'Polish', 'Paid Private Parking On-site']",
  'styles': "['Family', 'Mid-range']"}]